appium_server_url = 'http://localhost:4723'

number_1 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_1"]'
number_2 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_2"]'
number_3 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_3"]'
number_4 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_4"]'
number_5 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_5"]'
number_6 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_6"]'
number_7 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_7"]'
number_8 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_8"]'
number_9 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_9"]'
number_0 = '//android.widget.Button[@resource-id="com.google.android.calculator:id/digit_0"]'

plus = '//android.widget.Button[@content-desc="plus"]'
minus = '//android.widget.Button[@content-desc="minus"]'
multiplication = '//android.widget.Button[@content-desc="×"]'
division = '//android.widget.Button[@content-desc="divide"]'
equals = '//android.widget.Button[@content-desc="equals"]'
delete = '//android.widget.ImageButton[@content-desc="delete"]'
clear = '//android.widget.Button[@content-desc="clear"]'
